# Book settings
title: CPSC 2350 
author: Parsa Rajabi
logo: images/langara-logo.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false
  navbar_number_sections : false
  baseurl : "https://parsa-rajabi.github.io/cpsc-2350/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "Parsa-Rajabi/cpsc-2350"
    dokieli: true
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/firasm/jupyterbook_course_template
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      INSTRUCTOR: "Parsa Rajabi (he/his/him)"
      PRONOUNCE: "Pa-r-sa Ra-ja-bi"
      # OFFICE: "TBD"
      # PHONE: "N/A"
      COURSE_CODE: "CPSC 2350"
      SECTION: "M01"
      CREDITS: "3"
      TITLE: "Software Practices"
      PREREQS: "A minimum B grade in CPSC 1030 and 1045."
      # COREQS: "N/A"
      TERM: "2022 Winter Term 1"
      ROOM: "A274"
      MEETING_TIMES: "Saturdays, 1:30-3:20 pm PST"
      GRACE_PERIOD: "48 hour"
      # W_DATE_1: "11:59 PDT on January 22, 2021"
      # W_DATE_2: "11:59 PDT on March 26, 2021"
      # W_DATE_3: "11:59 PDT on March 26, 2021"
      EXAM_PERIOD: "April 8â€“23 2022"
      CANVAS_ID: "222094"
      CANVAS_LINK: "https://d2l.langara.bc.ca/d2l/home/CANVAS_ID"
      # ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      # ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      # COURSE_LINK: "https://firas.moosvi.com/courses/cosc123"
      # FORUM_LINK: "[Ed Discussion](https://edstem.org/us/join/fgh45hfgh)"
      # ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/xxxxxxxxxx)"
      # FORMAT: "Lectures, Labs, Tutorials and they will all be running online in this course."
      # ASSOCIATE_HEAD: "Jake Bobowski [jake.bobowski@ubc.ca](mailto:jake.bobowski@ubc.ca)"
      # ANON_FEEDBACK: "[feedback form](https://cbc.ca)"